### ISSUE TITLE
Cyclic reference with rustc 1.19.0-nightly (75b056812 2017-05-15)

### ISSUE THREAD

**Issue by theikkila** [sebcrozet/nalgebra#255] opened 2017-05-16 14:49 UTC
```
error[E0391]: unsupported cyclic reference between types/traits detected
   --> /Users/theikkila/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.5.1/src/structs/dmat.rs:137:5
    |
137 |     mij:   [N; 1 * 1],
    |     ^^^^^^^^^^^^^^^^^ cyclic reference
    |
note: the cycle begins when processing `structs::dmat::DMat1::mij`...
   --> /Users/theikkila/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.5.1/src/structs/dmat.rs:137:5
    |
137 |     mij:   [N; 1 * 1],
    |     ^^^^^^^^^^^^^^^^^
note: ...which then requires const-evaluating `structs::dmat::DMat1::{{initializer}}`...
   --> /Users/theikkila/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.5.1/src/structs/dmat.rs:137:16
    |
137 |     mij:   [N; 1 * 1],
    |                ^^^^^
note: ...which then requires processing `structs::dmat::DMat1::{{initializer}}`...
   --> /Users/theikkila/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.5.1/src/structs/dmat.rs:137:16
    |
137 |     mij:   [N; 1 * 1],
    |                ^^^^^
note: ...which then requires coherence checking all impls of trait `std::ops::Mul`...
note: ...which then requires processing `structs::dmat::DMat`...
   --> /Users/theikkila/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.5.1/src/structs/dmat.rs:21:1
    |
21  | / pub struct DMat<N> {
22  | |     nrows: usize,
23  | |     ncols: usize,
24  | |     mij:   Vec<N>
25  | | }
    | |_^
note: ...which then requires computing the variances for items in this crate...

```

**Comment by sebcrozet** [comment] 2017-05-16 16:07
You seem to be using a very old version of nalgebra. Uptdating to a newer one should help (beware the API changes though).

Anyway, looking at the errors this looks like a compiler bug (or a regression); especially if the stable compiler does not show any error.

**Comment by aepsil0n** [comment] 2017-07-28 17:05
@theikkila I will close this, since there was no further discussion of this.

Feel free to re-open in the unlikely event, that the bug should persist on the current version of `nalgebra`.

**Closed by aepsil0n** 2017-07-28 17:05 UTC
