### ISSUE TITLE
Seemingly incorrect orthographic matrix calculation.

### ISSUE THREAD

**Issue by palodequeso** [sebcrozet/nalgebra#79] opened 2015-01-23 13:49 UTC
I believe it's missing some values but perhaps it is by design. I have laid out the entire problem here:
http://pastebin.com/GHSrUp61

**Comment by sebcrozet** [comment] 2015-01-23 20:00
Given the current assumptions of the implementation of the orthographic matrix in `nalgebra`, this is not a bug. Those assumptions are that `bottom = -top = -height / 2` and `left = -right = -width / 2`. That way, the two "missing values" you pointed out are zeros.

Though I don't know whether this assumption feels too restrictive for the user or not. If so, it can be lifted to use top/down/left/right instead.

**Comment by palodequeso** [comment] 2015-01-23 20:09
It's not a huge deal, I can always modify my other maths to make this work. I'll leave it up to you. At the least I would document more what it does under the hood.

**Comment by sebcrozet** [comment] 2016-03-31 19:55
Fixed by #175 . We now use standard CG conventions.

**Closed by sebcrozet** 2016-03-31 19:55 UTC
